services:
  # ฐานข้อมูล MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./Backend
    volumes:
      - ./Backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/TypingGame
      - JWT_SECRET=3abc1485a33948924faf95b362002ac0d1e369e7abacde9da737f687c7fde318
      - PORT=5000
      - JWT_EXPIRES_IN=1d
      - FRONTEND_URL=http://localhost:5173
      - CHOKIDAR_USEPOLLING=true # เพิ่มบรรทัดนี้: ช่วยให้ Node.js ตรวจจับไฟล์แก้บน Windows ได้ชัวร์ขึ้น
    depends_on:
      - mongodb

  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_WATCH_USEPOLLING=true # เพิ่มบรรทัดนี้: บังคับให้ Vite ตรวจเช็คไฟล์ใหม่ตลอดเวลา (แก้ปัญหาแก้โค้ดแล้วหน้าเว็บไม่รีเฟรช)
    stdin_open: true 
    tty: true # เพิ่มบรรทัดนี้: ทำงานคู่กับ stdin_open เพื่อให้ Terminal ของ Vite เสถียรขึ้น
    depends_on:
      - backend

volumes:
  mongo-data: